language: node_js

sudo: false

branches:
  only:
  - master

cache:
  - npm

node_js:
  - "10"

before_script:
  - npm install
  - hexo cl

script:
  - hexo generate

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: public
  keep-history: false
  on:
    branch: master
